# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0003_auto_20160714_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='year',
            new_name='birth_year',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='rank_of_service',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='branch_of_service',
            new_name='service_branch',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='type_of_service',
            new_name='service_type',
        ),
    ]
