# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0005_auto_20160714_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_month',
            field=models.CharField(blank=True, choices=[(b'1', b'January'), (b'2', b'February'), (b'3', b'March'), (b'4', b'April'), (b'5', b'May'), (b'6', b'June'), (b'7', b'July'), (b'8', b'August'), (b'9', b'September'), (b'10', b'October'), (b'11', b'November'), (b'12', b'December')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ownership',
            field=models.CharField(blank=True, choices=[('RENT', 'Rent'), ('OWN', 'Own')], max_length=200, null=True),
        ),
    ]
