# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0007_auto_20160714_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_month',
            field=models.CharField(blank=True, choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=200, null=True),
        ),
    ]
