# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0008_auto_20160714_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='repay',
            field=models.CharField(blank=True, choices=[('MONTHLY ALLOTMENT', 'Monthly Allotment'), ('MONTHLY BANK ACH', 'Monthly Bank ACH'), ('THE FEDERAL SAVINGS BANK CHECKING ACCOUNT', 'The Federal Savings Bank Checking Account (save up to 10 percent on your loan)')], max_length=200, null=True),
        ),
    ]
