# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0011_auto_20160714_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='active_duty',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('yes', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='ownership',
            field=models.CharField(blank=True, choices=[('rent', 'Rent'), ('own', 'Own')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='rank',
            field=models.CharField(blank=True, choices=[('Rank of Service', 'rank 1'), ('2', 'rank 2'), ('3', 'rank 3'), ('4', 'rank 4')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='service_branch',
            field=models.CharField(blank=True, choices=[('Branch of Service', 'branch 1'), ('2', 'branch 2'), ('3', 'branch 3'), ('4', 'branch 4')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Type of Service', 'type 1'), ('2', 'type 2'), ('3', 'type 3'), ('4', 'type 4')], max_length=200, null=True),
        ),
    ]
