# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0012_auto_20160714_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='other_income',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('other', 'Other'), ('child_support', 'Child Support'), ('alimony', 'Alimony')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='reduced_income',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=200, null=True),
        ),
    ]
