# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frames', '0013_auto_20160715_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='credit_request_type',
            field=models.CharField(blank=True, choices=[('Type of Credit Requesting', 'credit request type 1'), ('2', 'credit request type 2'), ('3', 'credit request type 3'), ('4', 'credit request type 4')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='loan_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('auto_loan_new', 'Auto Loan (New)'), ('unsecured_personal_loan_new', 'Unsecured Personal Loan (New)'), ('secured_personal_loan', 'Secured Personal Loan'), ('auto_loan_refinance', 'Auto Loan (Refinance)'), ('unsecured_personal_loan_refinance', 'Unsecured Personal Loan (Refinance)'), ('student_loans', 'Student Loans'), ('home_improvement', 'Home Improvement'), ('other', 'Other')], max_length=154, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='repay',
            field=models.CharField(blank=True, choices=[('monthly_allotment', 'Monthly Allotment'), ('monthly_bank_ach', 'Monthly Bank ACH'), ('federal_savings', 'The Federal Savings Bank Checking Account (save up to 10 percent on your loan)')], max_length=200, null=True),
        ),
    ]
